[package]
name = "p256-arithmetic"
version = "0.1.0"
edition = "2021"

[dependencies]
group = { path = "../group" }
crypto-bigint = { version = "0.6.0-rc.6", features = [
    "alloc",
    "serde",
    "rand_core",
] }
sha2 = "0.10.8"
rand = "0.8.5"
