[package]
name = "proves-wasm"
version = "0.1.0"
edition = "2021"
[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-bindgen = "0.2.99"
proves = { path = "../proves" }
getrandom = { version = "*", features = ["js"] }
p256 = "0.13.2"
sha2 = "0.10.8"
