[package]
name = "tom256"
version = "0.1.0"
edition = "2021"

[dependencies]
crypto-bigint = { version = "0.6.0-rc.6", features = [
    "alloc",
    "serde",
    "rand_core",
] }
rand = "0.8.5"
group = { path = "../group" }
sha2 = "0.10.8"
